import { useState } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { ToggleButton } from "@/components/ToggleButton";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [on, setOn] = useState(false);
  console.log(styles);
  return (
    <>
      <Head>
        <title>Toggle Button</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div
          style={{
            padding: "15px",
            margin: "auto",
            maxWidth: "700px",
            lineHeight: "3",
          }}
        >
          <h1>Toggle Button</h1>
          <ToggleButton on={on} onToggle={() => setOn(!on)} />
          <h2>Status: {on ? "on" : "off"}</h2>
          <h4>
            Pro tip: change the theme of your OS to see the button in dark mode
          </h4>
        </div>
      </main>
    </>
  );
}
